GNSS L1 Position Resolver: algo.h File Reference
algo.h File Reference
Common includes and definitions for GNSS position solving algorithms.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdbool.h>
#include <time.h>
#include <unistd.h>
#include <sys/types.h>
#include <errno.h>
Macros
#define COLOR_RESET "\033[0m"
< Standard I/O functions
#define COLOR_GREEN "\033[1;32m"
#define COLOR_YELLOW "\033[1;33m"
#define COLOR_BLUE "\033[1;34m"
#define COLOR_RED "\033[1;31m"
Functions
void app_menu (void)
Application menu loop for selecting RTCM input source.
void app_cleanup (void)
Perform cleanup operations before application exit.
int serial_connect_mac (char *selected_port, size_t size)
List and connect to USB serial ports on macOS/Linux.
void * serial_connect (char *selected_port, size_t size)
Cross-platform serial connect wrapper.
FILE * file_connect (bool is_parsed)
Open an RTCM log file for reading.
int file_input_mode (bool is_parsed)
Main loop for processing a recorded RTCM input file.
Detailed Description
Common includes and definitions for GNSS position solving algorithms.
This header provides the standard system headers required across algorithm components including math functions, memory handling, and system types.
Definition in file algo.h.
Macro Definition Documentation
COLOR_BLUE
#define COLOR_BLUE "\033[1;34m"
Definition at line 28 of file algo.h.
Referenced by file_connect(), print_banner(), and prompt_choice().
COLOR_GREEN
#define COLOR_GREEN "\033[1;32m"
Definition at line 26 of file algo.h.
Referenced by app_cleanup(), app_menu(), file_connect(), file_input_mode(), and print_menu().
COLOR_RED
#define COLOR_RED "\033[1;31m"
Definition at line 29 of file algo.h.
Referenced by app_menu(), file_connect(), file_input_mode(), prompt_choice(), and sort_satellites().
COLOR_RESET
#define COLOR_RESET "\033[0m"
< Standard I/O functions
< Memory allocation, process control, conversions < String manipulation functions < Math functions such as sqrt, sin, cos < Boolean type support for C99 and above < Time and date functions < POSIX API (read, write, close, etc.) < System data types (pid_t, size_t, etc.) < Error number definitions
Definition at line 25 of file algo.h.
Referenced by app_cleanup(), app_menu(), file_connect(), file_input_mode(), print_banner(), print_menu(), prompt_choice(), read_next_rtcm_message(), and sort_satellites().
COLOR_YELLOW
#define COLOR_YELLOW "\033[1;33m"
Definition at line 27 of file algo.h.
Referenced by app_menu(), file_connect(), file_input_mode(), print_banner(), and read_next_rtcm_message().
Function Documentation
app_cleanup()
void app_cleanup (void)
Perform cleanup operations before application exit.
This function should be called at the end of the application's lifecycle. Currently, it only prints a confirmation message, but in a full deployment it can be expanded to include:
Memory deallocation
File handle closure
Hardware resource shutdown
Logging or telemetry flushing
Todo
Add actual resource cleanup when dynamic allocations or handles are introduced.
Definition at line 25 of file app_cleanup.c.
References COLOR_GREEN, and COLOR_RESET.
Referenced by main().
app_menu()
void app_menu (void)
Application menu loop for selecting RTCM input source.
Prints a banner and menu, then repeatedly prompts the user until a valid choice is entered. Dispatches to the respective handler for each menu option.
Todo
Implement Option 1 (Serial Port Input).
Implement Option 2 (Pre-recorded File Input, Raw Binary).
Definition at line 110 of file app_menu.c.
References COLOR_GREEN, COLOR_RED, COLOR_RESET, COLOR_YELLOW, file_input_mode(), print_banner(), print_menu(), and prompt_choice().
Referenced by main().
file_connect()
FILE * file_connect (bool is_parsed)
Open an RTCM log file for reading.
Prompts the user to provide a path to an RTCM log file. If the input is left blank, a default path is used. Retries up to MAX_RETRIES if the file cannot be opened. Supports two modes:
Parsed mode (is_parsed = true): opens the file in text mode ("r").
Raw mode (is_parsed = false): opens the file in binary mode ("rb").
Parameters
[in] is_parsed True to open a parsed text log file, false for raw binary.
Returns
FILE* Pointer to the opened file, or NULL on failure after all retries.
Todo
Implement raw binary RTCM parsing when is_parsed = false.
< Parsed text log
< Raw binary log
Definition at line 32 of file file_connect.c.
References COLOR_BLUE, COLOR_GREEN, COLOR_RED, COLOR_RESET, COLOR_YELLOW, DEFAULT_FILE_PATH, and MAX_RETRIES.
Referenced by file_input_mode().
file_input_mode()
int file_input_mode (bool is_parsed)
Main loop for processing a recorded RTCM input file.
This function opens the specified RTCM file and iteratively processes epochs by reading and parsing supported RTCM messages (e.g., MSM4). It prepares the observation data and then runs the solver and coordinate conversions.
Parameters
is_parsed Set to true if the file is in pre-parsed (text) format.
Returns
0 on success, 1 on error (open, read, sort, position, etc.).
Definition at line 39 of file file_input_mode.c.
References COLOR_GREEN, COLOR_RED, COLOR_RESET, COLOR_YELLOW, eph_history, estimate_receiver_positions(), file_connect(), gps_list, msm1_history, msm4_history, n_times, read_next_rtcm_message(), satellite_orbit_eci(), satellite_position_ecef(), satellite_position_eci(), sort_satellites(), write_pseudorange_time_km(), write_receiver_ecef_epoch_km(), write_receiver_track_ecef(), write_receiver_track_geo(), write_sat_orbits(), and write_sat_xyz_km().
Referenced by app_menu().
serial_connect()
void * serial_connect (char * selected_port, size_t size)
Cross-platform serial connect wrapper.
Dispatches to the platform-specific implementation and returns an opaque handle the caller can store. On Windows this is a HANDLE. On POSIX this is a file descriptor cast to void* via intptr_t.
Parameters
[out] selected_port Buffer to receive the chosen port path/name.
[in] size Size of selected_port buffer in bytes.
Returns
Opaque handle to the opened port, or NULL on failure.
Definition at line 226 of file serial_connect.c.
References serial_connect_mac().
serial_connect_mac()
int serial_connect_mac (char * selected_port, size_t size)
List and connect to USB serial ports on macOS/Linux.
Scans /dev for tty.usb* and ttyUSB* device nodes, prompts for a choice, opens the device, and applies 9600 8-N-1 with basic raw settings.
Parameters
[out] selected_port Buffer to receive the selected device path.
[in] size Size of selected_port buffer in bytes.
Returns
File descriptor (>=0) on success, or -1 on failure.
Definition at line 119 of file serial_connect.c.
Referenced by serial_connect().