GNSS L1 Position Resolver: all_plots.c File Reference
all_plots.c File Reference
Writers for receiver and satellite tracks used by plotting scripts.
#include "../include/algo.h"
#include "../include/df_parser.h"
#include "../include/rtcm_reader.h"
#include "../include/satellites.h"
#include "../include/receiver.h"
Functions
int write_receiver_track_ecef (const char *path, int n_epochs)
Write receiver ECEF track (meters) to a file.
int write_sat_orbits (const char *path)
Write satellite ECEF samples (meters) as one big file.
int write_receiver_track_geo (const char *path, int n_epochs)
Write receiver geographic track (lat, lon in degrees).
static double m_to_km (double v_m)
int write_receiver_ecef_epoch_km (const char *path, int n_epochs)
Write receiver ECEF (kilometers) with epoch index prefix.
int write_sat_xyz_km (const char *path)
Write satellite XYZ (kilometers).
int write_pseudorange_time_km (const char *path)
(Optional) Write pseudorange vs.
Variables
latlonalt_position_t latlonalt_positions
LLA results per epoch.
sat_ecef_history_t sat_ecef_positions [MAX_SAT+1]
Satellite ECEF histories.
estimated_position_t estimated_positions_ecef
Receiver ECEF track.
Detailed Description
Writers for receiver and satellite tracks used by plotting scripts.
This module dumps computed GNSS artifacts to simple, columnar text files that gnuplot (or any plotting tool) can consume. It includes:
Receiver ECEF track (meters)
Receiver ECEF track with epoch index (kilometers)
Receiver geographic track (lat, lon in degrees)
Satellite orbits / ECEF samples (meters)
Satellite XYZ (kilometers)
(Optional) Pseudorange vs. time (kilometers)
The routines are intentionally minimal and perform basic validation to avoid writing all-zero or non-finite rows.
Definition in file all_plots.c.
Function Documentation
m_to_km()
static double m_to_km (double v_m) inline static
Definition at line 161 of file all_plots.c.
Referenced by write_receiver_ecef_epoch_km(), and write_sat_xyz_km().
write_pseudorange_time_km()
int write_pseudorange_time_km (const char * path)
(Optional) Write pseudorange vs.
time per PRN (kilometers).
Output format (per line): PRN t(s) PR_km Blocks are separated by blank lines.
Parameters
path Destination file path.
Returns
0 on success, -1 if file open failed.
Note
Time units: currently writes DF004/collected time as seconds if t is already in seconds. If your timestamps are in milliseconds, scale accordingly.
Definition at line 247 of file all_plots.c.
References gps_list, MAX_EPOCHS, MAX_SAT, gps_satellite_data_t::pseudoranges, and gps_satellite_data_t::times_of_pseudorange.
Referenced by file_input_mode().
write_receiver_ecef_epoch_km()
int write_receiver_ecef_epoch_km (const char * path, int n_epochs)
Write receiver ECEF (kilometers) with epoch index prefix.
Output format (per line): epoch_index X_km Y_km Z_km
Parameters
path Destination file path.
n_epochs Number of epochs to write.
Returns
0 on success, -1 if file open failed.
Definition at line 172 of file all_plots.c.
References estimated_positions_ecef, m_to_km(), estimated_position_t::x, estimated_position_t::y, and estimated_position_t::z.
Referenced by file_input_mode().
write_receiver_track_ecef()
int write_receiver_track_ecef (const char * path, int n_epochs)
Write receiver ECEF track (meters) to a file.
Output format (per line): X Y Z
Parameters
path Destination file path.
n_epochs Number of epochs to write.
Returns
0 on success, -1 on failure (open error or no lines written).
Definition at line 37 of file all_plots.c.
References estimated_positions_ecef, estimated_position_t::x, estimated_position_t::y, and estimated_position_t::z.
Referenced by file_input_mode().
write_receiver_track_geo()
int write_receiver_track_geo (const char * path, int n_epochs)
Write receiver geographic track (lat, lon in degrees).
Output format (per line): lat lon
Parameters
path Destination file path.
n_epochs Number of epochs to write.
Returns
0 on success, -1 if file open failed or no finite rows written.
Definition at line 123 of file all_plots.c.
References latlonalt_position_t::lat, latlonalt_positions, and latlonalt_position_t::lon.
Referenced by file_input_mode().
write_sat_orbits()
int write_sat_orbits (const char * path)
Write satellite ECEF samples (meters) as one big file.
Output format (per line): PRN X Y Z Sats are separated by blank lines.
Parameters
path Destination file path.
Returns
0 on success, -1 on failure to open.
Definition at line 85 of file all_plots.c.
References MAX_EPOCHS, MAX_SAT, sat_ecef_positions, sat_ecef_history_t::x, sat_ecef_history_t::y, and sat_ecef_history_t::z.
Referenced by file_input_mode().
write_sat_xyz_km()
int write_sat_xyz_km (const char * path)
Write satellite XYZ (kilometers).
Output format (per line): PRN X_km Y_km Z_km Sats are separated by blank lines.
Parameters
path Destination file path.
Returns
0 on success, -1 if file open failed.
Definition at line 203 of file all_plots.c.
References m_to_km(), MAX_EPOCHS, MAX_SAT, and sat_ecef_positions.
Referenced by file_input_mode().
Variable Documentation
estimated_positions_ecef
estimated_position_t estimated_positions_ecef extern
Receiver ECEF track.
Definition at line 31 of file receiver_position.c.
Referenced by estimate_receiver_positions(), write_receiver_ecef_epoch_km(), and write_receiver_track_ecef().
latlonalt_positions
latlonalt_position_t latlonalt_positions extern
LLA results per epoch.
Definition at line 32 of file receiver_position.c.
Referenced by estimate_receiver_positions(), and write_receiver_track_geo().
sat_ecef_positions
sat_ecef_history_t sat_ecef_positions[MAX_SAT+1] extern
Satellite ECEF histories.
Definition at line 15 of file satellites.c.
Referenced by write_sat_orbits(), and write_sat_xyz_km().