GNSS L1 Position Resolver: app_menu.c File Reference
app_menu.c File Reference
Menu interface for selecting RTCM input source in the GNSS application.
#include "../include/algo.h"
Macros
#define INPUT_BUF_SZ 64
Functions
static void print_banner (void)
Print program banner with title and supported features.
static void print_menu (void)
Print the main RTCM input selection menu.
static int prompt_choice (void)
Prompt the user for a menu choice and parse input.
void app_menu (void)
Application menu loop for selecting RTCM input source.
Detailed Description
Menu interface for selecting RTCM input source in the GNSS application.
Provides a terminal-driven menu for choosing how RTCM data is fed into the GNSS L1 positioning resolver. At present, only the "Pre-recorded File" modes are functional. Serial input (Option 1) and live parsed input (Option 2) are defined in the menu but not yet implemented.
Usage flow:
Displays a banner and usage notice
Displays an input menu
Prompts the user for a choice
Dispatches to the appropriate handler function
Note
Option 1 (Serial Port Input) is not implemented yet.
Option 2 (Pre-recorded File Input, text format) is placeholder-only.
Option 3 (Pre-recorded File Input, parsed with PyRTCM) is supported.
Definition in file app_menu.c.
Macro Definition Documentation
INPUT_BUF_SZ
#define INPUT_BUF_SZ 64
Definition at line 24 of file app_menu.c.
Referenced by prompt_choice().
Function Documentation
app_menu()
void app_menu (void)
Application menu loop for selecting RTCM input source.
Prints a banner and menu, then repeatedly prompts the user until a valid choice is entered. Dispatches to the respective handler for each menu option.
Todo
Implement Option 1 (Serial Port Input).
Implement Option 2 (Pre-recorded File Input, Raw Binary).
Definition at line 110 of file app_menu.c.
References COLOR_GREEN, COLOR_RED, COLOR_RESET, COLOR_YELLOW, file_input_mode(), print_banner(), print_menu(), and prompt_choice().
Referenced by main().
print_banner()
static void print_banner (void) static
Print program banner with title and supported features.
Definition at line 27 of file app_menu.c.
References COLOR_BLUE, COLOR_RESET, and COLOR_YELLOW.
Referenced by app_menu().
print_menu()
static void print_menu (void) static
Print the main RTCM input selection menu.
Definition at line 39 of file app_menu.c.
References COLOR_GREEN, and COLOR_RESET.
Referenced by app_menu().
prompt_choice()
static int prompt_choice (void) static
Prompt the user for a menu choice and parse input.
Reads from stdin and validates the entered choice. Handles whitespace, newline, and EOF gracefully.
Returns
Parsed menu option in [1..4], or 4 if input is closed (EOF).
Definition at line 60 of file app_menu.c.
References COLOR_BLUE, COLOR_RED, COLOR_RESET, and INPUT_BUF_SZ.
Referenced by app_menu().