GNSS L1 Position Resolver: df_parser.c File Reference
df_parser.c File Reference
Parses RTCM 1019 and 1074 messages from text-formatted input lines.
#include "../include/algo.h"
#include "../include/df_parser.h"
Functions
int parse_rtcm_1002 (const char *line, rtcm_1002_msm1_t *msm1)
Parses a single RTCM 1002 MSM1 line into a structured observation object.
int parse_rtcm_1074 (const char *line, rtcm_1074_msm4_t *msm4)
Parses a single RTCM 1074 MSM4 line into a structured observation object.
int parse_rtcm_1019 (const char *line, rtcm_1019_ephemeris_t *eph)
Parses a single RTCM 1019 line into a structured ephemeris object.
double compute_pseudorange (uint32_t integer_ms, double mod1s_sec, double fine_sec)
Computes the pseudorange from the given parameters.
double compute_pseudorange_msm1 (double amb, double rem)
Computes the pseudorange for an RTCM 1002 (MSM1) observation.
int store_ephemeris (const rtcm_1019_ephemeris_t *new_eph)
Stores or updates the ephemeris data for a given satellite.
int store_msm4 (const rtcm_1074_msm4_t *new_msm4)
Stores the entire MSM4 struct for each PRN at the current epoch.
int store_msm1 (const rtcm_1002_msm1_t *new_msm1)
Stores the entire MSM1 struct for each PRN at the current epoch.
int store_pseudorange (const rtcm_1074_msm4_t *new_msm4)
Stores pseudorange for all satellites in the MSM4 message at the current epoch.
int store_pseudorange_msm1 (const rtcm_1002_msm1_t *new_msm1)
Stores pseudorange for all satellites in the MSM1 message at the current epoch.
Variables
bool eph_available [MAX_SAT+1] = {0}
size_t msm4_count [MAX_SAT+1] = {0}
size_t msm1_count [MAX_SAT+1] = {0}
double pseudorange_history [MAX_SAT+1][MAX_EPOCHS] = {{0}}
size_t pseudorange_count [MAX_SAT+1] = {0}
rtcm_1002_msm1_t msm1_history [MAX_SAT+1][MAX_EPOCHS] = {{{0}}}
rtcm_1074_msm4_t msm4_history [MAX_SAT+1][MAX_EPOCHS] = {{{0}}}
rtcm_1019_ephemeris_t eph_table [MAX_SAT+1] = {{0}}
uint8_t observation_type = 0
Detailed Description
Parses RTCM 1019 and 1074 messages from text-formatted input lines.
This module provides parsing logic for the following specific RTCM message types:
RTCM 1019: Broadcast ephemeris messages (used for GPS satellite position)
RTCM 1002: Legacy observation messages (used for GPS L1 pseudorange and phase)
RTCM 1074: MSM4 observation messages (used for GPS L1 pseudorange and phase)
The input is assumed to be text-format (e.g., exported from parsed binary logs), and each line contains a full RTCM message with labeled fields (DFxxx).
Output is stored in well-defined structures for further positioning analysis.
Definition in file df_parser.c.
Function Documentation
compute_pseudorange()
double compute_pseudorange (uint32_t integer_ms, double mod1s_sec, double fine_sec)
Computes the pseudorange from the given parameters.
This function calculates the pseudorange using the formula: Pseudorange = c * (integer_ms * 1e-3 + mod1s_sec + fine_sec)
Parameters
integer_ms Rough range integer in milliseconds.
mod1s_sec Pseudorange modulo 1 second.
fine_sec Pseudorange residuals in seconds scaled by speed of light.
Returns
The computed pseudorange in meters.
Definition at line 365 of file df_parser.c.
References SPEED_OF_LIGHT.
Referenced by parse_rtcm_1074().
compute_pseudorange_msm1()
double compute_pseudorange_msm1 (double amb, double rem)
Computes the pseudorange for an RTCM 1002 (MSM1) observation.
Calculates the pseudorange by combining the rough range integer (in milliseconds) with the pseudorange remainder (in meters), applying the appropriate speed-of-light scaling to the integer term.
Formula: pseudorange = (amb * 299792.458) + rem
Parameters
amb Rough range integer in milliseconds.
rem Pseudorange remainder in meters.
Returns
Pseudorange in meters.
Definition at line 384 of file df_parser.c.
References SPEED_OF_LIGHT.
Referenced by parse_rtcm_1002(), print_msm1(), and store_pseudorange_msm1().
parse_rtcm_1002()
int parse_rtcm_1002 (const char * line, rtcm_1002_msm1_t * msm1)
Parses a single RTCM 1002 MSM1 line into a structured observation object.
Parses a line of RTCM 1002 (GPS L1) text-formatted input into a structured observation object.
This function extracts the MSM1 header and all per-satellite fields (PRN, signal ID, pseudorange remainder, phase range difference, lock time, ambiguity, and CNR) from the provided text-formatted RTCM message.
Parameters
line Input string containing the RTCM 1002 MSM1 message.
msm1 Pointer to the MSM1 observation structure to populate.
Returns
0 on success, non-zero on failure.
Definition at line 42 of file df_parser.c.
References rtcm_1002_msm1_t::ambiguities, rtcm_1002_msm1_t::cnr, compute_pseudorange_msm1(), EXTRACT, rtcm_1002_msm1_t::lock_time, rtcm_1002_msm1_t::msg_type, rtcm_1002_msm1_t::num_satellites, rtcm_1002_msm1_t::phase_pr_diff, rtcm_1002_msm1_t::pseudoranges, rtcm_1002_msm1_t::remainders, rtcm_1002_msm1_t::sig_id, rtcm_1002_msm1_t::smooth_interval, rtcm_1002_msm1_t::smooth_interval_flag, rtcm_1002_msm1_t::station_id, rtcm_1002_msm1_t::svs, rtcm_1002_msm1_t::sync_gps_message_flag, and rtcm_1002_msm1_t::time_of_week.
Referenced by read_next_rtcm_message().
parse_rtcm_1019()
int parse_rtcm_1019 (const char * line, rtcm_1019_ephemeris_t * eph)
Parses a single RTCM 1019 line into a structured ephemeris object.
Parses a line of RTCM 1019 text-formatted input into a structured ephemeris object.
This function extracts all defined DF fields from a line containing a text-formatted RTCM 1019 message and fills the provided structure accordingly.
Parameters
line Input string with the RTCM message content.
eph Pointer to output structure to populate.
Returns
0 on success, non-zero on failure.
Definition at line 301 of file df_parser.c.
References rtcm_1019_ephemeris_t::argument_of_periapsis, rtcm_1019_ephemeris_t::eccentricity, EXTRACT, rtcm_1019_ephemeris_t::gps_af0, rtcm_1019_ephemeris_t::gps_af1, rtcm_1019_ephemeris_t::gps_af2, rtcm_1019_ephemeris_t::gps_cic, rtcm_1019_ephemeris_t::gps_cis, rtcm_1019_ephemeris_t::gps_code_l2, rtcm_1019_ephemeris_t::gps_crc, rtcm_1019_ephemeris_t::gps_crs, rtcm_1019_ephemeris_t::gps_cuc, rtcm_1019_ephemeris_t::gps_cus, rtcm_1019_ephemeris_t::gps_delta_n, rtcm_1019_ephemeris_t::gps_eccentricity, rtcm_1019_ephemeris_t::gps_i0, rtcm_1019_ephemeris_t::gps_idot, rtcm_1019_ephemeris_t::gps_iodc, rtcm_1019_ephemeris_t::gps_iode, rtcm_1019_ephemeris_t::gps_l2p_data_flag, rtcm_1019_ephemeris_t::gps_m0, rtcm_1019_ephemeris_t::gps_omega, rtcm_1019_ephemeris_t::gps_omega0, rtcm_1019_ephemeris_t::gps_omega_dot, rtcm_1019_ephemeris_t::gps_sqrt_a, rtcm_1019_ephemeris_t::gps_sv_acc, rtcm_1019_ephemeris_t::gps_sv_health, rtcm_1019_ephemeris_t::gps_tgd, rtcm_1019_ephemeris_t::gps_toc, rtcm_1019_ephemeris_t::gps_toe, rtcm_1019_ephemeris_t::gps_wn, rtcm_1019_ephemeris_t::inclination, rtcm_1019_ephemeris_t::mean_anomaly, rtcm_1019_ephemeris_t::msg_type, PI, rtcm_1019_ephemeris_t::right_ascension_of_ascending_node, rtcm_1019_ephemeris_t::satellite_id, rtcm_1019_ephemeris_t::semi_major_axis, rtcm_1019_ephemeris_t::sv, rtcm_1019_ephemeris_t::time_of_week, rtcm_1019_ephemeris_t::time_since_epoch, and rtcm_1019_ephemeris_t::week_number.
Referenced by read_next_rtcm_message().
parse_rtcm_1074()
int parse_rtcm_1074 (const char * line, rtcm_1074_msm4_t * msm4)
Parses a single RTCM 1074 MSM4 line into a structured observation object.
Parses a line of RTCM 1074 MSM4 text-formatted input into a structured observation object.
This function extracts the MSM4 header and all per-cell data (pseudorange, carrier phase, lock time, CNR, etc.) for each satellite-signal combination.
Parameters
line Input string with the RTCM message content.
msm4 Pointer to output structure to populate.
Returns
0 on success, non-zero on failure.
Definition at line 123 of file df_parser.c.
References rtcm_1074_msm4_t::cell_prn, rtcm_1074_msm4_t::cell_sig, rtcm_1074_msm4_t::clk_steering_flag, rtcm_1074_msm4_t::cnr, compute_pseudorange(), rtcm_1074_msm4_t::external_clk_flag, EXTRACT, rtcm_1074_msm4_t::gps_epoch_time, rtcm_1074_msm4_t::iods_reserved, rtcm_1074_msm4_t::lock_time, rtcm_1074_msm4_t::msg_type, rtcm_1074_msm4_t::msm_sync_flag, rtcm_1074_msm4_t::n_cell, rtcm_1074_msm4_t::n_sat, rtcm_1074_msm4_t::n_sig, rtcm_1074_msm4_t::phase_range, rtcm_1074_msm4_t::prn, rtcm_1074_msm4_t::pseudorange, rtcm_1074_msm4_t::pseudorange_fine, rtcm_1074_msm4_t::pseudorange_integer, rtcm_1074_msm4_t::pseudorange_mod_1s, rtcm_1074_msm4_t::reserved_DF001_07, rtcm_1074_msm4_t::station_id, and rtcm_1074_msm4_t::time_of_pseudorange.
Referenced by read_next_rtcm_message().
store_ephemeris()
int store_ephemeris (const rtcm_1019_ephemeris_t * new_eph)
Stores or updates the ephemeris data for a given satellite.
This function always updates the ephemeris for the specified satellite, regardless of IODE/IODC. It ensures the latest data is always stored.
Parameters
new_eph Pointer to the new ephemeris data to store.
Returns
0 on success, -1 if input is NULL, -2 if PRN is out of range (1-32).
Definition at line 404 of file df_parser.c.
References eph_history_t::count, eph_history_t::eph, eph_available, eph_history, eph_table, MAX_EPH_HISTORY, MAX_SAT, and rtcm_1019_ephemeris_t::satellite_id.
Referenced by read_next_rtcm_message().
store_msm1()
int store_msm1 (const rtcm_1002_msm1_t * new_msm1)
Stores the entire MSM1 struct for each PRN at the current epoch.
This function appends the full MSM1 struct for each PRN in the message to a history array, so you can later access all MSM1 fields for every satellite and epoch.
Parameters
new_msm1 Pointer to the new MSM1 observation data to store.
Returns
0 on success, -1 if input is NULL.
Definition at line 477 of file df_parser.c.
References MAX_EPOCHS, MAX_SAT, msm1_count, msm1_history, rtcm_1002_msm1_t::num_satellites, and rtcm_1002_msm1_t::svs.
Referenced by read_next_rtcm_message().
store_msm4()
int store_msm4 (const rtcm_1074_msm4_t * new_msm4)
Stores the entire MSM4 struct for each PRN at the current epoch.
This function appends the full MSM4 struct for each PRN in the message to a history array, so you can later access all MSM4 fields for every satellite and epoch.
Parameters
new_msm4 Pointer to the new MSM4 observation data to store.
Returns
0 on success, -1 if input is NULL.
Definition at line 442 of file df_parser.c.
References MAX_EPOCHS, MAX_SAT, msm4_count, msm4_history, rtcm_1074_msm4_t::n_sat, and rtcm_1074_msm4_t::prn.
Referenced by read_next_rtcm_message().
store_pseudorange()
int store_pseudorange (const rtcm_1074_msm4_t * new_msm4)
Stores pseudorange for all satellites in the MSM4 message at the current epoch.
This function appends the pseudorange for each PRN in the message to a history array, so you can later plot the time series for each satellite.
Parameters
new_msm4 Pointer to the new MSM4 observation data to store.
Returns
0 on success, -1 if input is NULL.
Definition at line 517 of file df_parser.c.
References MAX_EPOCHS, MAX_SAT, rtcm_1074_msm4_t::n_sat, rtcm_1074_msm4_t::prn, rtcm_1074_msm4_t::pseudorange, pseudorange_count, and pseudorange_history.
store_pseudorange_msm1()
int store_pseudorange_msm1 (const rtcm_1002_msm1_t * new_msm1)
Stores pseudorange for all satellites in the MSM1 message at the current epoch.
Computes pseudorange from MSM1 rough-range ambiguity (ms) and remainder, then appends the value for each PRN to a per-PRN history buffer for later plotting.
Parameters
new_msm1 Pointer to the new MSM1 observation data to store.
Returns
0 on success, -1 if input is NULL.
Definition at line 552 of file df_parser.c.
References rtcm_1002_msm1_t::ambiguities, compute_pseudorange_msm1(), MAX_EPOCHS, MAX_SAT, rtcm_1002_msm1_t::num_satellites, pseudorange_count, pseudorange_history, rtcm_1002_msm1_t::remainders, and rtcm_1002_msm1_t::svs.
Variable Documentation
eph_available
bool eph_available[MAX_SAT+1] = {0}
Definition at line 20 of file df_parser.c.
Referenced by store_ephemeris().
eph_table
rtcm_1019_ephemeris_t eph_table[MAX_SAT+1] = {{0}}
Definition at line 27 of file df_parser.c.
Referenced by store_ephemeris().
msm1_count
size_t msm1_count[MAX_SAT+1] = {0}
Definition at line 22 of file df_parser.c.
Referenced by sort_satellites(), and store_msm1().
msm1_history
rtcm_1002_msm1_t msm1_history[MAX_SAT+1][MAX_EPOCHS] = {{{0}}}
Definition at line 25 of file df_parser.c.
Referenced by store_msm1().
msm4_count
size_t msm4_count[MAX_SAT+1] = {0}
Definition at line 21 of file df_parser.c.
Referenced by sort_satellites(), and store_msm4().
msm4_history
rtcm_1074_msm4_t msm4_history[MAX_SAT+1][MAX_EPOCHS] = {{{0}}}
Definition at line 26 of file df_parser.c.
Referenced by file_input_mode(), and store_msm4().
observation_type
uint8_t observation_type = 0
Definition at line 28 of file df_parser.c.
pseudorange_count
size_t pseudorange_count[MAX_SAT+1] = {0}
Definition at line 24 of file df_parser.c.
Referenced by pr_count_for_prn(), print_all_stored_pseudoranges(), store_pseudorange(), and store_pseudorange_msm1().
pseudorange_history
double pseudorange_history[MAX_SAT+1][MAX_EPOCHS] = {{0}}
Definition at line 23 of file df_parser.c.
Referenced by print_all_stored_pseudoranges(), store_pseudorange(), and store_pseudorange_msm1().