GNSS L1 Position Resolver: file_input_mode.c File Reference
file_input_mode.c File Reference
Handles RTCM MSM4 file input, step-by-step parsing and position resolution.
#include "../include/algo.h"
#include "../include/df_parser.h"
#include "../include/rtcm_reader.h"
#include "../include/satellites.h"
#include "../include/receiver.h"
#include "../include/plots.h"
Functions
int file_input_mode (bool is_parsed)
Main loop for processing a recorded RTCM input file.
Variables
int n_times
Detailed Description
Handles RTCM MSM4 file input, step-by-step parsing and position resolution.
This function is triggered when the user selects "File Input" from the application menu. It opens a pre-recorded RTCM file (text or binary), reads each epoch's MSM4 message(s), extracts relevant GNSS observations, and calculates the receiver position using the least squares method.
The resulting receiver position is output in geodetic coordinates (decimal degrees).
All major processing stages (file handling, message reading, observation parsing, position solving, and coordinate conversion) are handled by separate modules for clarity and maintainability.
Definition in file file_input_mode.c.
Function Documentation
file_input_mode()
int file_input_mode (bool is_parsed)
Main loop for processing a recorded RTCM input file.
This function opens the specified RTCM file and iteratively processes epochs by reading and parsing supported RTCM messages (e.g., MSM4). It prepares the observation data and then runs the solver and coordinate conversions.
Parameters
is_parsed Set to true if the file is in pre-parsed (text) format.
Returns
0 on success, 1 on error (open, read, sort, position, etc.).
Definition at line 39 of file file_input_mode.c.
References COLOR_GREEN, COLOR_RED, COLOR_RESET, COLOR_YELLOW, eph_history, estimate_receiver_positions(), file_connect(), gps_list, msm1_history, msm4_history, n_times, read_next_rtcm_message(), satellite_orbit_eci(), satellite_position_ecef(), satellite_position_eci(), sort_satellites(), write_pseudorange_time_km(), write_receiver_ecef_epoch_km(), write_receiver_track_ecef(), write_receiver_track_geo(), write_sat_orbits(), and write_sat_xyz_km().
Referenced by app_menu().
Variable Documentation
n_times
int n_times extern
Definition at line 33 of file receiver_position.c.
Referenced by estimate_receiver_positions(), and file_input_mode().