GNSS L1 Position Resolver: plots.h File Reference
plots.h File Reference
Functions
int write_receiver_track_ecef (const char *path, int n_epochs)
Write receiver ECEF track (meters) to a file.
int write_sat_orbits (const char *path)
Write satellite ECEF samples (meters) as one big file.
int write_receiver_track_geo (const char *path, int n_epochs)
Write receiver geographic track (lat, lon in degrees).
int write_receiver_ecef_epoch_km (const char *path, int n_epochs)
Write receiver ECEF (kilometers) with epoch index prefix.
int write_sat_xyz_km (const char *path)
Write satellite XYZ (kilometers).
int write_pseudorange_time_km (const char *path)
(Optional) Write pseudorange vs.
Function Documentation
write_pseudorange_time_km()
int write_pseudorange_time_km (const char * path)
(Optional) Write pseudorange vs.
time per PRN (kilometers).
Output format (per line): PRN t(s) PR_km Blocks are separated by blank lines.
Parameters
path Destination file path.
Returns
0 on success, -1 if file open failed.
Note
Time units: currently writes DF004/collected time as seconds if t is already in seconds. If your timestamps are in milliseconds, scale accordingly.
Definition at line 247 of file all_plots.c.
References gps_list, MAX_EPOCHS, MAX_SAT, gps_satellite_data_t::pseudoranges, and gps_satellite_data_t::times_of_pseudorange.
Referenced by file_input_mode().
write_receiver_ecef_epoch_km()
int write_receiver_ecef_epoch_km (const char * path, int n_epochs)
Write receiver ECEF (kilometers) with epoch index prefix.
Output format (per line): epoch_index X_km Y_km Z_km
Parameters
path Destination file path.
n_epochs Number of epochs to write.
Returns
0 on success, -1 if file open failed.
Definition at line 172 of file all_plots.c.
References estimated_positions_ecef, m_to_km(), estimated_position_t::x, estimated_position_t::y, and estimated_position_t::z.
Referenced by file_input_mode().
write_receiver_track_ecef()
int write_receiver_track_ecef (const char * path, int n_epochs)
Write receiver ECEF track (meters) to a file.
Output format (per line): X Y Z
Parameters
path Destination file path.
n_epochs Number of epochs to write.
Returns
0 on success, -1 on failure (open error or no lines written).
Definition at line 37 of file all_plots.c.
References estimated_positions_ecef, estimated_position_t::x, estimated_position_t::y, and estimated_position_t::z.
Referenced by file_input_mode().
write_receiver_track_geo()
int write_receiver_track_geo (const char * path, int n_epochs)
Write receiver geographic track (lat, lon in degrees).
Output format (per line): lat lon
Parameters
path Destination file path.
n_epochs Number of epochs to write.
Returns
0 on success, -1 if file open failed or no finite rows written.
Definition at line 123 of file all_plots.c.
References latlonalt_position_t::lat, latlonalt_positions, and latlonalt_position_t::lon.
Referenced by file_input_mode().
write_sat_orbits()
int write_sat_orbits (const char * path)
Write satellite ECEF samples (meters) as one big file.
Output format (per line): PRN X Y Z Sats are separated by blank lines.
Parameters
path Destination file path.
Returns
0 on success, -1 on failure to open.
Definition at line 85 of file all_plots.c.
References MAX_EPOCHS, MAX_SAT, sat_ecef_positions, sat_ecef_history_t::x, sat_ecef_history_t::y, and sat_ecef_history_t::z.
Referenced by file_input_mode().
write_sat_xyz_km()
int write_sat_xyz_km (const char * path)
Write satellite XYZ (kilometers).
Output format (per line): PRN X_km Y_km Z_km Sats are separated by blank lines.
Parameters
path Destination file path.
Returns
0 on success, -1 if file open failed.
Definition at line 203 of file all_plots.c.
References m_to_km(), MAX_EPOCHS, MAX_SAT, and sat_ecef_positions.
Referenced by file_input_mode().