GNSS L1 Position Resolver: print_utils.c File Reference
print_utils.c File Reference
Handles RTCM MSM4 file input, step-by-step parsing and position resolution.
#include "../include/algo.h"
#include "../include/df_parser.h"
Functions
void print_ephemeris (const rtcm_1019_ephemeris_t *eph)
Prints the contents of a parsed RTCM 1019 ephemeris structure.
static const char * msm1_sig_name (uint8_t sig_id)
Prints the contents of a parsed RTCM 1002 (MSM1 GPS L1) observation.
void print_msm1 (const rtcm_1002_msm1_t *msm1)
Prints the contents of a parsed RTCM 1002 (GPS L1) legacy observation structure.
void print_msm4 (const rtcm_1074_msm4_t *msm4)
Prints the contents of a parsed RTCM 1074 MSM4 observation structure.
void print_all_stored_pseudoranges (void)
Prints the stored pseudoranges for all satellites.
void print_all_stored_ephemeris (void)
Prints the full ephemeris history for all PRNs.
Detailed Description
Handles RTCM MSM4 file input, step-by-step parsing and position resolution.
This function is triggered when the user selects "File Input" from the application menu. It opens a pre-recorded RTCM binary file, reads each epoch's MSM4 message, extracts relevant GNSS observations, and calculates the receiver position using the least squares method. The resulting position is printed in geodetic coordinates (decimal degrees).
All major steps (reading, parsing, solving) are delegated to their respective modules to maintain modularity and educational clarity.
Definition in file print_utils.c.
Function Documentation
msm1_sig_name()
static const char * msm1_sig_name (uint8_t sig_id) static
Prints the contents of a parsed RTCM 1002 (MSM1 GPS L1) observation.
Uses the provided rtcm_1002_msm1_t fields (no assumptions). For each satellite, it also computes pseudorange with compute_pseudorange_msm1() from DF014 (ambiguity, ms) and DF011 (remainder, m) and shows the stored value.
Definition at line 83 of file print_utils.c.
Referenced by print_msm1().
print_all_stored_ephemeris()
void print_all_stored_ephemeris (void)
Prints the full ephemeris history for all PRNs.
Iterates over all PRNs and prints every stored ephemeris entry from eph_history[].
Definition at line 235 of file print_utils.c.
References rtcm_1019_ephemeris_t::argument_of_periapsis, eph_history_t::count, rtcm_1019_ephemeris_t::eccentricity, eph_history_t::eph, eph_history, rtcm_1019_ephemeris_t::gps_idot, rtcm_1019_ephemeris_t::gps_omega_dot, rtcm_1019_ephemeris_t::gps_toe, rtcm_1019_ephemeris_t::inclination, MAX_SAT, rtcm_1019_ephemeris_t::mean_anomaly, rtcm_1019_ephemeris_t::right_ascension_of_ascending_node, rtcm_1019_ephemeris_t::semi_major_axis, rtcm_1019_ephemeris_t::time_of_week, and rtcm_1019_ephemeris_t::week_number.
print_all_stored_pseudoranges()
void print_all_stored_pseudoranges (void)
Prints the stored pseudoranges for all satellites.
This function iterates through the global pseudorange table and prints the details for each satellite that has valid ephemeris data.
Definition at line 210 of file print_utils.c.
References MAX_SAT, pseudorange_count, and pseudorange_history.
print_ephemeris()
void print_ephemeris (const rtcm_1019_ephemeris_t * eph)
Prints the contents of a parsed RTCM 1019 ephemeris structure.
This function outputs the ephemeris data in a human-readable format, useful for debugging and verification purposes.
Parameters
eph Pointer to the ephemeris structure to print.
Definition at line 27 of file print_utils.c.
References rtcm_1019_ephemeris_t::gps_af0, rtcm_1019_ephemeris_t::gps_af1, rtcm_1019_ephemeris_t::gps_af2, rtcm_1019_ephemeris_t::gps_cic, rtcm_1019_ephemeris_t::gps_cis, rtcm_1019_ephemeris_t::gps_code_l2, rtcm_1019_ephemeris_t::gps_crc, rtcm_1019_ephemeris_t::gps_crs, rtcm_1019_ephemeris_t::gps_cuc, rtcm_1019_ephemeris_t::gps_cus, rtcm_1019_ephemeris_t::gps_delta_n, rtcm_1019_ephemeris_t::gps_eccentricity, rtcm_1019_ephemeris_t::gps_fit_interval, rtcm_1019_ephemeris_t::gps_i0, rtcm_1019_ephemeris_t::gps_idot, rtcm_1019_ephemeris_t::gps_iodc, rtcm_1019_ephemeris_t::gps_iode, rtcm_1019_ephemeris_t::gps_l2p_data_flag, rtcm_1019_ephemeris_t::gps_m0, rtcm_1019_ephemeris_t::gps_omega, rtcm_1019_ephemeris_t::gps_omega0, rtcm_1019_ephemeris_t::gps_omega_dot, rtcm_1019_ephemeris_t::gps_sqrt_a, rtcm_1019_ephemeris_t::gps_sv_acc, rtcm_1019_ephemeris_t::gps_sv_health, rtcm_1019_ephemeris_t::gps_tgd, rtcm_1019_ephemeris_t::gps_toc, rtcm_1019_ephemeris_t::gps_toe, rtcm_1019_ephemeris_t::gps_wn, and rtcm_1019_ephemeris_t::satellite_id.
print_msm1()
void print_msm1 (const rtcm_1002_msm1_t * msm1)
Prints the contents of a parsed RTCM 1002 (GPS L1) legacy observation structure.
This function outputs the stored pseudorange, carrier phase, and related observation fields from the provided RTCM 1002 structure in a human-readable format, useful for debugging and verification.
Parameters
msm1 Pointer to the RTCM 1002 observation structure to print.
Definition at line 97 of file print_utils.c.
References rtcm_1002_msm1_t::ambiguities, rtcm_1002_msm1_t::cnr, compute_pseudorange_msm1(), rtcm_1002_msm1_t::lock_time, MAX_SIG, rtcm_1002_msm1_t::msg_type, msm1_sig_name(), rtcm_1002_msm1_t::num_satellites, rtcm_1002_msm1_t::phase_pr_diff, rtcm_1002_msm1_t::pseudoranges, rtcm_1002_msm1_t::remainders, rtcm_1002_msm1_t::sig_id, rtcm_1002_msm1_t::smooth_interval, rtcm_1002_msm1_t::smooth_interval_flag, rtcm_1002_msm1_t::svs, rtcm_1002_msm1_t::sync_gps_message_flag, and rtcm_1002_msm1_t::time_of_week.
print_msm4()
void print_msm4 (const rtcm_1074_msm4_t * msm4)
Prints the contents of a parsed RTCM 1074 MSM4 observation structure.
This function outputs the observation data in a human-readable format, useful for debugging and verification purposes.
Parameters
msm4 Pointer to the MSM4 observation structure to print.
Definition at line 159 of file print_utils.c.
References rtcm_1074_msm4_t::cell_prn, rtcm_1074_msm4_t::cell_sig, rtcm_1074_msm4_t::clk_steering_flag, rtcm_1074_msm4_t::cnr, rtcm_1074_msm4_t::external_clk_flag, rtcm_1074_msm4_t::gps_epoch_time, rtcm_1074_msm4_t::lock_time, rtcm_1074_msm4_t::msg_type, rtcm_1074_msm4_t::msm_sync_flag, rtcm_1074_msm4_t::n_cell, rtcm_1074_msm4_t::n_sat, rtcm_1074_msm4_t::n_sig, rtcm_1074_msm4_t::prn, rtcm_1074_msm4_t::pseudorange, rtcm_1074_msm4_t::pseudorange_fine, rtcm_1074_msm4_t::pseudorange_integer, rtcm_1074_msm4_t::pseudorange_mod_1s, rtcm_1074_msm4_t::smooth_interval_flag, and rtcm_1074_msm4_t::station_id.