GNSS L1 Position Resolver: receiver.h File Reference
receiver.h File Reference
#include "../include/algo.h"
#include "../include/satellites.h"
#include <assert.h>
#include <math.h>
#include <float.h>
#include <stdio.h>
#include <string.h>
Data Structures
struct estimated_position_t
struct latlonalt_position_t
Macros
#define ITERATIONS 10
#define MIN_SATS 4
#define RAD2DEG (180.0 / M_PI)
#define ENABLE_LSQ_DEBUG 1
#define MAX_UNIQUE_EPOCHS 100000
#define MAX_SV_USED MAX_SAT
#define DLOG(...)
Functions
int estimate_receiver_positions (void)
void ecef_to_geodetic (double x, double y, double z, double *lat_deg, double *lon_deg, double *alt_m)
Variables
estimated_position_t estimated_positions_ecef
latlonalt_position_t latlonalt_positions
int n_times
Macro Definition Documentation
DLOG
#define DLOG (...)
Value:
    do            \
    {             \
    } while (0)
Definition at line 28 of file receiver.h.
ENABLE_LSQ_DEBUG
#define ENABLE_LSQ_DEBUG 1
Definition at line 16 of file receiver.h.
ITERATIONS
#define ITERATIONS 10
Definition at line 12 of file receiver.h.
MAX_SV_USED
#define MAX_SV_USED MAX_SAT
Definition at line 18 of file receiver.h.
MAX_UNIQUE_EPOCHS
#define MAX_UNIQUE_EPOCHS 100000
Definition at line 17 of file receiver.h.
Referenced by collect_unique_pr_times_ms(), and estimate_receiver_positions().
MIN_SATS
#define MIN_SATS 4
Definition at line 13 of file receiver.h.
RAD2DEG
#define RAD2DEG (180.0 / M_PI)
Definition at line 14 of file receiver.h.
Function Documentation
ecef_to_geodetic()
void ecef_to_geodetic (double x, double y, double z, double * lat_deg, double * lon_deg, double * alt_m)
Definition at line 25 of file ecef_to_latlong.c.
References PI.
Referenced by estimate_receiver_positions().
estimate_receiver_positions()
int estimate_receiver_positions (void)
Definition at line 197 of file receiver_position.c.
References collect_unique_pr_times_ms(), ecef_to_geodetic(), estimated_positions_ecef, gps_list, ITERATIONS, latlonalt_position_t::lat, latlonalt_positions, latlonalt_position_t::lon, MAX_EPOCHS, MAX_SAT, MAX_UNIQUE_EPOCHS, n_times, norm3(), pinv_normal_eq_apply(), pr_count_for_prn(), gps_satellite_data_t::pseudoranges, sat_ecef_positions, estimated_position_t::x, sat_ecef_history_t::x, estimated_position_t::y, sat_ecef_history_t::y, estimated_position_t::z, and sat_ecef_history_t::z.
Referenced by file_input_mode().
Variable Documentation
estimated_positions_ecef
estimated_position_t estimated_positions_ecef extern
Definition at line 31 of file receiver_position.c.
latlonalt_positions
latlonalt_position_t latlonalt_positions extern
Definition at line 32 of file receiver_position.c.
n_times
int n_times extern
Definition at line 33 of file receiver_position.c.