GNSS L1 Position Resolver: receiver_position.c File Reference
receiver_position.c File Reference
Estimate GNSS receiver positions using pseudorange measurements.
#include "../include/satellites.h"
#include "../include/receiver.h"
#include "../include/algo.h"
Macros
#define ITERATIONS 10
Functions
static int cmp_u32 (const void *a, const void *b)
static int pr_count_for_prn (int prn)
static int collect_unique_pr_times_ms (const gps_satellite_data_t glist[MAX_SAT+1], uint32_t out_times_ms[MAX_UNIQUE_EPOCHS])
static double norm3 (const double v[3])
static int invert_4x4 (const double A[4][4], double inv[4][4])
static int pinv_normal_eq_apply (int m, double G[][4], const double *y, double out[4])
int estimate_receiver_positions (void)
Variables
gps_satellite_data_t gps_list [MAX_SAT+1]
sat_ecef_history_t sat_ecef_positions [MAX_SAT+1]
Satellite ECEF histories.
size_t pseudorange_count [MAX_SAT+1]
estimated_position_t estimated_positions_ecef = {0}
Receiver ECEF track.
latlonalt_position_t latlonalt_positions = {0}
LLA results per epoch.
int n_times = 0
Detailed Description
Estimate GNSS receiver positions using pseudorange measurements.
This module implements the C equivalent of the Python estimate_positions function. It:
Collects unique pseudorange epochs across all satellites
Aligns satellite ECEF positions to the pseudorange epochs
Runs an iterative least-squares solver (Newton method) to estimate receiver position and clock bias per epoch
The output is stored in estimated_positions_ecef as ECEF coordinates.
Note
This implementation uses normal equations with a 4x4 matrix inverse for the pseudoinverse step. It mirrors the Python logic, with optional diagnostic prints disabled by default.
Author
Ade
Date
2025-08-23
Definition in file receiver_position.c.
Macro Definition Documentation
ITERATIONS
#define ITERATIONS 10
Definition at line 35 of file receiver_position.c.
Referenced by estimate_receiver_positions().
Function Documentation
cmp_u32()
static int cmp_u32 (const void * a, const void * b) static
Definition at line 39 of file receiver_position.c.
Referenced by collect_unique_pr_times_ms().
collect_unique_pr_times_ms()
static int collect_unique_pr_times_ms (const gps_satellite_data_t glist[MAX_SAT+1], uint32_t out_times_ms[MAX_UNIQUE_EPOCHS]) static
Definition at line 58 of file receiver_position.c.
References cmp_u32(), MAX_SAT, MAX_UNIQUE_EPOCHS, and pr_count_for_prn().
Referenced by estimate_receiver_positions().
estimate_receiver_positions()
int estimate_receiver_positions (void)
Definition at line 197 of file receiver_position.c.
References collect_unique_pr_times_ms(), ecef_to_geodetic(), estimated_positions_ecef, gps_list, ITERATIONS, latlonalt_position_t::lat, latlonalt_positions, latlonalt_position_t::lon, MAX_EPOCHS, MAX_SAT, MAX_UNIQUE_EPOCHS, n_times, norm3(), pinv_normal_eq_apply(), pr_count_for_prn(), gps_satellite_data_t::pseudoranges, sat_ecef_positions, estimated_position_t::x, sat_ecef_history_t::x, estimated_position_t::y, sat_ecef_history_t::y, estimated_position_t::z, and sat_ecef_history_t::z.
Referenced by file_input_mode().
invert_4x4()
static int invert_4x4 (const double A[4][4], double inv[4][4]) static
Definition at line 98 of file receiver_position.c.
Referenced by pinv_normal_eq_apply().
norm3()
static double norm3 (const double v[3]) inline static
Definition at line 92 of file receiver_position.c.
Referenced by estimate_receiver_positions().
pinv_normal_eq_apply()
static int pinv_normal_eq_apply (int m, double G[][4], const double * y, double out[4]) static
Definition at line 152 of file receiver_position.c.
References invert_4x4(), and MAX_SAT.
Referenced by estimate_receiver_positions().
pr_count_for_prn()
static int pr_count_for_prn (int prn) inline static
Definition at line 45 of file receiver_position.c.
References gps_list, MAX_EPOCHS, and pseudorange_count.
Referenced by collect_unique_pr_times_ms(), and estimate_receiver_positions().
Variable Documentation
estimated_positions_ecef
estimated_position_t estimated_positions_ecef = {0}
Receiver ECEF track.
Definition at line 31 of file receiver_position.c.
Referenced by estimate_receiver_positions(), write_receiver_ecef_epoch_km(), and write_receiver_track_ecef().
gps_list
gps_satellite_data_t gps_list[MAX_SAT+1] extern
Definition at line 13 of file satellites.c.
Referenced by estimate_receiver_positions(), populate_ephemeris_series_from_history(), pr_count_for_prn(), print_gps_list(), and sort_satellites().
latlonalt_positions
latlonalt_position_t latlonalt_positions = {0}
LLA results per epoch.
Definition at line 32 of file receiver_position.c.
Referenced by estimate_receiver_positions(), and write_receiver_track_geo().
n_times
int n_times = 0
Definition at line 33 of file receiver_position.c.
Referenced by estimate_receiver_positions(), and file_input_mode().
pseudorange_count
size_t pseudorange_count[MAX_SAT+1] extern
Definition at line 24 of file df_parser.c.
Referenced by pr_count_for_prn(), store_pseudorange(), and store_pseudorange_msm1().
sat_ecef_positions
sat_ecef_history_t sat_ecef_positions[MAX_SAT+1] extern
Satellite ECEF histories.
Definition at line 15 of file satellites.c.
Referenced by estimate_receiver_positions().