GNSS L1 Position Resolver: rtcm_reader.c File Reference
rtcm_reader.c File Reference
Reads RTCM messages from a text-formatted file and dispatches parsing for known message types.
#include "../include/algo.h"
#include "../include/rtcm_reader.h"
#include "../include/df_parser.h"
Functions
int read_next_rtcm_message (FILE *fp)
Reads the next valid RTCM message line from file and parses it if supported.
Detailed Description
Reads RTCM messages from a text-formatted file and dispatches parsing for known message types.
This function handles the input of RTCM messages in text format (one per line), as exported from logs or test files. It identifies supported message types (currently 1019 and 1074), and calls the appropriate parser function to extract useful GNSS data structures for later processing.
Unsupported or malformed lines are safely skipped. Ephemeris and MSM4 messages are handled separately.
Definition in file rtcm_reader.c.
Function Documentation
read_next_rtcm_message()
int read_next_rtcm_message (FILE * fp)
Reads the next valid RTCM message line from file and parses it if supported.
Currently supports:
RTCM 1019: Ephemeris (GPS)
RTCM 1074: MSM4 (GPS L1 pseudorange and phase)
Lines not matching these types are skipped. Each line should contain a complete message.
Parameters
fp Pointer to an open file for reading RTCM text lines.
Returns
0 on successful read and parse, non-zero otherwise.
Definition at line 30 of file rtcm_reader.c.
References COLOR_RESET, COLOR_YELLOW, observation_type, parse_rtcm_1002(), parse_rtcm_1019(), parse_rtcm_1074(), store_ephemeris(), store_msm1(), and store_msm4().
Referenced by file_input_mode().