GNSS L1 Position Resolver: rtcm_reader.h File Reference
rtcm_reader.h File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
int read_next_rtcm_message (FILE *fp)
Reads the next valid RTCM message line from file and parses it if supported.
Function Documentation
read_next_rtcm_message()
int read_next_rtcm_message (FILE * fp)
Reads the next valid RTCM message line from file and parses it if supported.
Currently supports:
RTCM 1019: Ephemeris (GPS)
RTCM 1074: MSM4 (GPS L1 pseudorange and phase)
Lines not matching these types are skipped. Each line should contain a complete message.
Parameters
fp Pointer to an open file for reading RTCM text lines.
Returns
0 on successful read and parse, non-zero otherwise.
Definition at line 30 of file rtcm_reader.c.
References COLOR_RESET, COLOR_YELLOW, observation_type, parse_rtcm_1002(), parse_rtcm_1019(), parse_rtcm_1074(), store_ephemeris(), store_msm1(), and store_msm4().
Referenced by file_input_mode().