GNSS L1 Position Resolver: satellites.h File Reference
satellites.h File Reference
#include "../include/df_parser.h"
#include "../include/algo.h"
Data Structures
struct gps_satellite_data_t
struct sat_eci_history_t
struct sat_ecef_history_t
struct sat_orbit_pqw_history_t
struct sat_orbit_eci_history_t
Macros
#define EARTH_MASS 5.9722e24
#define GRAVITATIONAL_CONSTANT 6.67430e-11
#define OMEGA_EARTH 7.2921151467e-5
#define MU (EARTH_MASS * GRAVITATIONAL_CONSTANT)
Functions
int sort_satellites (eph_history_t *eph_history, rtcm_1074_msm4_t msm4_history[MAX_SAT][MAX_EPOCHS], rtcm_1002_msm1_t msm1_history[MAX_SAT][MAX_EPOCHS])
void print_gps_list (void)
Prints the GPS satellite data summary.
int satellite_position_eci (const gps_satellite_data_t gps_lists[])
void mat3x3_vec3_mult (const double mat[3][3], const double vec[3], double out[3])
int satellite_position_ecef (const gps_satellite_data_t gps_lists[MAX_SAT+1])
int satellite_orbit_eci (const gps_satellite_data_t gps_lists[])
Variables
gps_satellite_data_t gps_list [MAX_SAT+1]
sat_eci_history_t sat_eci_positions [MAX_SAT+1]
sat_ecef_history_t sat_ecef_positions [MAX_SAT+1]
sat_orbit_pqw_history_t sat_orbit_pqw_positions [MAX_SAT+1]
sat_orbit_eci_history_t sat_orbit_eci_positions [MAX_SAT+1]
Macro Definition Documentation
EARTH_MASS
#define EARTH_MASS 5.9722e24
Definition at line 28 of file satellites.h.
GRAVITATIONAL_CONSTANT
#define GRAVITATIONAL_CONSTANT 6.67430e-11
Definition at line 29 of file satellites.h.
MU
#define MU (EARTH_MASS * GRAVITATIONAL_CONSTANT)
Definition at line 33 of file satellites.h.
Referenced by satellite_position_eci().
OMEGA_EARTH
#define OMEGA_EARTH 7.2921151467e-5
Definition at line 30 of file satellites.h.
Function Documentation
mat3x3_vec3_mult()
void mat3x3_vec3_mult (const double mat[3][3], const double vec[3], double out[3])
Definition at line 16 of file satellite_position_eci.c.
print_gps_list()
void print_gps_list (void)
Prints the GPS satellite data summary.
This function prints the pseudorange table (rows with valid PR) and then prints a Python-style ephemeris series that lists all unique TOE entries.
Definition at line 227 of file satellites.c.
References gps_satellite_data_t::argument_of_periapsis, gps_satellite_data_t::eccentricities, gps_list, gps_satellite_data_t::inclinations, MAX_EPOCHS, MAX_SAT, gps_satellite_data_t::mean_anomalies, gps_satellite_data_t::right_ascension_of_ascending_node, gps_satellite_data_t::semi_major_axes, and gps_satellite_data_t::times_of_ephemeris.
satellite_orbit_eci()
int satellite_orbit_eci (const gps_satellite_data_t gps_lists[])
Definition at line 18 of file satellite_orbit_eci.c.
References gps_satellite_data_t::argument_of_periapsis, gps_satellite_data_t::eccentricities, gps_satellite_data_t::inclinations, mat3x3_vec3_mult(), MAX_SAT, sat_orbit_pqw_history_t::p, sat_orbit_pqw_history_t::q, gps_satellite_data_t::right_ascension_of_ascending_node, sat_orbit_eci_positions, sat_orbit_pqw_positions, gps_satellite_data_t::semi_major_axes, sat_orbit_pqw_history_t::w, sat_orbit_eci_history_t::x, sat_orbit_eci_history_t::y, and sat_orbit_eci_history_t::z.
Referenced by file_input_mode().
satellite_position_ecef()
int satellite_position_ecef (const gps_satellite_data_t gps_lists[MAX_SAT+1])
Definition at line 32 of file satellite_position_ecef.c.
References mat3x3_vec3_mult(), MAX_EPOCHS, MAX_SAT, normalize_time_seconds(), sat_ecef_positions, sat_eci_positions, sat_ecef_history_t::t_ms, sat_ecef_history_t::x, sat_eci_history_t::x, sat_ecef_history_t::y, sat_eci_history_t::y, sat_ecef_history_t::z, and sat_eci_history_t::z.
Referenced by file_input_mode().
satellite_position_eci()
int satellite_position_eci (const gps_satellite_data_t gps_lists[])
Definition at line 41 of file satellite_position_eci.c.
References rtcm_1019_ephemeris_t::argument_of_periapsis, rtcm_1019_ephemeris_t::eccentricity, eph_history_t::eph, eph_history, find_closest_eph_idx(), rtcm_1019_ephemeris_t::gps_toe, rtcm_1019_ephemeris_t::inclination, mat3x3_vec3_mult(), MAX_EPOCHS, MAX_SAT, rtcm_1019_ephemeris_t::mean_anomaly, MU, rtcm_1019_ephemeris_t::right_ascension_of_ascending_node, sat_eci_positions, rtcm_1019_ephemeris_t::semi_major_axis, gps_satellite_data_t::times_of_pseudorange, sat_eci_history_t::x, sat_eci_history_t::y, and sat_eci_history_t::z.
Referenced by file_input_mode().
sort_satellites()
int sort_satellites (eph_history_t * eph_history, rtcm_1074_msm4_t msm4_history[MAX_SAT][MAX_EPOCHS], rtcm_1002_msm1_t msm1_history[MAX_SAT][MAX_EPOCHS])
Definition at line 77 of file satellites.c.
References gps_satellite_data_t::argument_of_periapsis, rtcm_1019_ephemeris_t::argument_of_periapsis, COLOR_RED, COLOR_RESET, gps_satellite_data_t::eccentricities, rtcm_1019_ephemeris_t::eccentricity, eph_history_t::eph, eph_history, find_closest_eph_idx(), gps_list, rtcm_1019_ephemeris_t::gps_toe, rtcm_1019_ephemeris_t::inclination, gps_satellite_data_t::inclinations, MAX_EPOCHS, MAX_SAT, gps_satellite_data_t::mean_anomalies, rtcm_1019_ephemeris_t::mean_anomaly, msm1_count, msm4_count, observation_type, populate_ephemeris_series_from_history(), gps_satellite_data_t::prn, gps_satellite_data_t::pseudoranges, gps_satellite_data_t::right_ascension_of_ascending_node, rtcm_1019_ephemeris_t::right_ascension_of_ascending_node, gps_satellite_data_t::semi_major_axes, rtcm_1019_ephemeris_t::semi_major_axis, gps_satellite_data_t::times_of_ephemeris, and gps_satellite_data_t::times_of_pseudorange.
Referenced by file_input_mode().
Variable Documentation
gps_list
gps_satellite_data_t gps_list[MAX_SAT+1] extern
Definition at line 13 of file satellites.c.
Referenced by file_input_mode(), and write_pseudorange_time_km().
sat_ecef_positions
sat_ecef_history_t sat_ecef_positions[MAX_SAT+1] extern
Definition at line 15 of file satellites.c.
Referenced by satellite_position_ecef().
sat_eci_positions
sat_eci_history_t sat_eci_positions[MAX_SAT+1] extern
Definition at line 14 of file satellites.c.
Referenced by satellite_position_eci().
sat_orbit_eci_positions
sat_orbit_eci_history_t sat_orbit_eci_positions[MAX_SAT+1] extern
Definition at line 17 of file satellites.c.
Referenced by satellite_orbit_eci().
sat_orbit_pqw_positions
sat_orbit_pqw_history_t sat_orbit_pqw_positions[MAX_SAT+1] extern
Definition at line 16 of file satellites.c.
Referenced by satellite_orbit_eci().