GNSS L1 Position Resolver: satellite_orbit_eci.c File Reference
satellite_orbit_eci.c File Reference
Computes the full satellite orbit for each satellite using the EPH data.
#include "../include/satellites.h"
#include "../include/algo.h"
#include "../include/df_parser.h"
#include "../include/rtcm_reader.h"
Functions
void mat3x3_vec3_mult (const double mat[3][3], const double vec[3], double out[3])
int satellite_orbit_eci (const gps_satellite_data_t gps_lists[])
Detailed Description
Computes the full satellite orbit for each satellite using the EPH data.
For each PRN that has ephemeris, we sweep true anomaly f from 0..2π, compute PQW coordinates (in meters), then rotate to ECI with: Rz(-ω) -> Rx(-i) -> Rz(-Ω)
Definition in file satellite_orbit_eci.c.
Function Documentation
mat3x3_vec3_mult()
void mat3x3_vec3_mult (const double mat[3][3], const double vec[3], double out[3]) extern
Definition at line 16 of file satellite_position_eci.c.
Referenced by satellite_orbit_eci().
satellite_orbit_eci()
int satellite_orbit_eci (const gps_satellite_data_t gps_lists[])
Definition at line 18 of file satellite_orbit_eci.c.
References gps_satellite_data_t::argument_of_periapsis, gps_satellite_data_t::eccentricities, gps_satellite_data_t::inclinations, mat3x3_vec3_mult(), MAX_SAT, sat_orbit_pqw_history_t::p, sat_orbit_pqw_history_t::q, gps_satellite_data_t::right_ascension_of_ascending_node, sat_orbit_eci_positions, sat_orbit_pqw_positions, gps_satellite_data_t::semi_major_axes, sat_orbit_pqw_history_t::w, sat_orbit_eci_history_t::x, sat_orbit_eci_history_t::y, and sat_orbit_eci_history_t::z.
Referenced by file_input_mode().