GNSS L1 Position Resolver: satellite_position_eci.c File Reference
satellite_position_eci.c File Reference
#include "../include/satellites.h"
#include "../include/algo.h"
#include "../include/df_parser.h"
#include "../include/rtcm_reader.h"
Functions
void mat3x3_vec3_mult (const double mat[3][3], const double vec[3], double out[3])
static int find_closest_eph_idx (const eph_history_t *hist, uint32_t pseudorange_time)
int satellite_position_eci (const gps_satellite_data_t gps_lists[])
Function Documentation
find_closest_eph_idx()
static int find_closest_eph_idx (const eph_history_t * hist, uint32_t pseudorange_time) static
Definition at line 25 of file satellite_position_eci.c.
References eph_history_t::count, eph_history_t::eph, and rtcm_1019_ephemeris_t::gps_toe.
Referenced by satellite_position_eci().
mat3x3_vec3_mult()
void mat3x3_vec3_mult (const double mat[3][3], const double vec[3], double out[3])
Definition at line 16 of file satellite_position_eci.c.
Referenced by satellite_orbit_eci(), satellite_position_ecef(), and satellite_position_eci().
satellite_position_eci()
int satellite_position_eci (const gps_satellite_data_t gps_lists[])
Definition at line 41 of file satellite_position_eci.c.
References rtcm_1019_ephemeris_t::argument_of_periapsis, rtcm_1019_ephemeris_t::eccentricity, eph_history_t::eph, eph_history, find_closest_eph_idx(), rtcm_1019_ephemeris_t::gps_toe, rtcm_1019_ephemeris_t::inclination, mat3x3_vec3_mult(), MAX_EPOCHS, MAX_SAT, rtcm_1019_ephemeris_t::mean_anomaly, MU, rtcm_1019_ephemeris_t::right_ascension_of_ascending_node, sat_eci_positions, rtcm_1019_ephemeris_t::semi_major_axis, gps_satellite_data_t::times_of_pseudorange, sat_eci_history_t::x, sat_eci_history_t::y, and sat_eci_history_t::z.
Referenced by file_input_mode().