GNSS L1 Position Resolver: satellite_position_ecef.c File Reference
satellite_position_ecef.c File Reference
Converts the satellite position from ECI coordinates to ECEF frame.
#include "../include/satellites.h"
#include "../include/algo.h"
#include "../include/df_parser.h"
#include "../include/rtcm_reader.h"
Functions
void mat3x3_vec3_mult (const double mat[3][3], const double vec[3], double out[3])
static double normalize_time_seconds (double t)
int satellite_position_ecef (const gps_satellite_data_t gps_lists[MAX_SAT+1])
Variables
sat_eci_history_t sat_eci_positions [MAX_SAT+1]
Detailed Description
Converts the satellite position from ECI coordinates to ECEF frame.
Mirrors the Python implementation: theta = (t / 86400) % 1 * 2*pi (solar day, not sidereal) and performs ecef = eci * Rz(theta). Since our helper does column-vector math (out = R * v), we multiply by Rz^T to match the Python row*matrix result.
Definition in file satellite_position_ecef.c.
Function Documentation
mat3x3_vec3_mult()
void mat3x3_vec3_mult (const double mat[3][3], const double vec[3], double out[3]) extern
Definition at line 16 of file satellite_position_eci.c.
Referenced by satellite_position_ecef(), and satellite_position_eci().
normalize_time_seconds()
static double normalize_time_seconds (double t) inline static
Definition at line 22 of file satellite_position_ecef.c.
Referenced by satellite_position_ecef().
satellite_position_ecef()
int satellite_position_ecef (const gps_satellite_data_t gps_lists[MAX_SAT+1])
Definition at line 32 of file satellite_position_ecef.c.
References mat3x3_vec3_mult(), MAX_EPOCHS, MAX_SAT, normalize_time_seconds(), sat_ecef_positions, sat_eci_positions, sat_ecef_history_t::t_ms, sat_ecef_history_t::x, sat_eci_history_t::x, sat_ecef_history_t::y, sat_eci_history_t::y, sat_ecef_history_t::z, and sat_eci_history_t::z.
Referenced by file_input_mode().
Variable Documentation
sat_eci_positions
sat_eci_history_t sat_eci_positions[MAX_SAT+1] extern
Definition at line 14 of file satellites.c.
Referenced by satellite_position_ecef().